version: '3'

services:
  mariadb:
    image: mariadb
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: on-failure
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql/'
    networks:
      - nat
  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    restart: on-failure
    ports:
      - '9000:9000'
    volumes:
      - 'wp:/var/www/html'
    networks:
      - nat
    depends_on:
      - mariadb
  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - '443:443'
    depends_on:
      - wordpress
    restart: on-failure
    volumes:
      - 'wp:/var/www/html'
    networks:
      - nat


volumes:
  db:
    driver: local
    driver_opts:
      device: "/home/sismaili/data/db"
      type: none
      o: bind
  wp:
    driver: local
    driver_opts:
      device: "/home/sismaili/data/wordpress"
      type: none
      o: bind
networks:
  nat:
    driver: bridge
