version: '3'

services:
  # nginx:
  #   image: nginx
  #   build: ./requirements/nginx
  #   container_name: nginx
  #   env_file:
  #     - .env
  #   ports:
  #     - 443:443
  #   restart: on-failure
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: on-failure
    ports:
      - '3306:3306'
    volumes:
      - 'data_db:/var/lib/mysql/'
    networks:
      - nat
  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress_ct
    env_file:
      - .env
    restart: on-failure
    ports:
      - '9000:9000'
    volumes:
      - 'data_wp:/var/www/html'
    networks:
      - nat
    depends_on:
      - mariadb


volumes:
  data_db:
    driver: local
    driver_opts:
      device: "/home/sismaili/data/db"
      type: none
      o: bind
  data_wp:
    driver: local
    driver_opts:
      device: "/home/sismaili/data/wordpress"
      type: none
      o: bind
networks:
  nat:
    driver: bridge
