version: '3'

services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: on-failure
    volumes:
      - 'db:/var/lib/mysql'
    ports:
      - '3306:3306'
    networks:
      - net
  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    restart: on-failure
    ports:
      - '9000:9000'
    volumes:
      - 'wordpress:/var/www/html'
    depends_on:
      - mariadb
    networks:
      - net
  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - '443:443'
    depends_on:
      - wordpress
    restart: on-failure
    volumes:
      - 'wordpress:/var/www/html'
    networks:
      - net
  redis:
    image: redis
    build: ./requirements/bonus/redis
    container_name: redis
    restart: on-failure
    ports:
      - '6379:6379'
    networks:
      - net
  adminer:
    image: adminer
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: on-failure
    depends_on:
      - mariadb
    ports:
      - '8080:8080'
    networks:
      - net

volumes:
  db:
    driver: local
    driver_opts:
      device: "/home/sismaili/data/db"
      type: none
      o: bind
  wordpress:
    driver: local
    driver_opts:
      device: "/home/sismaili/data/wordpress"
      type: none
      o: bind
networks:
  net:
    driver: bridge

