version: '3'

services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    volumes:
      - 'db:/var/lib/mysql'
    ports:
      - '3306:3306'
    networks:
      - nat
  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    restart: on-failure
    ports:
      - '9000:9000'
    volumes:
      - 'wordpress:/var/www/html'
    depends_on:
      - mariadb
    networks:
      - nat
  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - '443:443'
    depends_on:
      - wordpress
    restart: on-failure
    volumes:
      - 'wordpress:/var/www/html'
    networks:
      - nat

volumes:
  db:
    driver: local
    driver_opts:
      device: "/Users/sismaili/Desktop/Inception/data/db"
      type: none
      o: bind
  wordpress:
    driver: local
    driver_opts:
      device: "/Users/sismaili/Desktop/Inception/data/wordpress"
      type: none
      o: bind
networks:
  nat:
    driver: bridge

