version: '3'

services:
  # nginx:
  #   image: nginx
  #   build: ./requirements/nginx
  #   container_name: nginx
  #   env_file:
  #     - .env
  #   ports:
  #     - 443:443
  #   restart: on-failure
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: on-failure
    ports:
      - '3306:3306'
    volumes:
      - data_db:/var/lib/mysql/
    networks:
      - nat

volumes:
  data_db:
    driver: local
    driver_opts:
      device: "/Users/sismaili/Desktop/Inception/srcs/data_db"
      type: none
      o: bind

networks:
  nat:
    driver: bridge